[mypy]
python_version = 3.11
strict = true
files = nifblend/bridge, nifblend/io, nifblend/format
exclude = (?x)(
    nifblend/vendor/.*
  | nifblend/tests/.*
  )

# Blender's bpy module has stubs from fake-bpy-module-latest, but they're not always complete
[mypy-bpy.*]
ignore_missing_imports = true

[mypy-mathutils.*]
ignore_missing_imports = true

[mypy-bmesh.*]
ignore_missing_imports = true
